[package]
name = "bevy_fog_of_war"
version = "0.0.1"
edition = "2021"
readme = "README.md"
description = "A fog of war implementation for the Bevy game engine. "
authors = ["FoxZoOL <zhooul@gmail.com>"]
keywords = ["bevy", "shade", "plugin"]
categories = ["game-development"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/foxzool/bevy_fog_of_war"
documentation = "https://docs.rs/bevy_fog_of_war"

[features]
default = ["2d", "debug_chunk"]
2d = []
3d = []
debug_chunk = []

[dependencies]
bevy = { version = "0.15", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_mesh_picking_backend",
    "bevy_pbr",
    "bevy_picking",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_sprite_picking_backend",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_picking_backend",
    "bevy_window",
    "bevy_winit",
    "custom_cursor",
    "default_font",
    "hdr",
    "multi_threaded",
    "png",
    "smaa_luts",
    "sysinfo_plugin",
    "tonemapping_luts",
    "webgl2",
    "x11"
] }
bevy_pbr = "0.15"
bevy_render = "0.15"
bytemuck = "1.21.0"

[dev-dependencies]
bevy-inspector-egui = "0.28"

[[example]]
name = "fog_of_war_2d"
path = "examples/2d.rs"
required-features = ["2d"]