[package]
name = "fog-of-war"
version = "0.1.0"
edition = "2024"

[features]
default = []
2d = []
3d = []


[dependencies]
bevy = { version = "0.15", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_color",
    "bevy_core_pipeline",
    "bevy_gilrs",
    "bevy_gizmos",
    "bevy_gltf",
    "bevy_mesh_picking_backend",
    "bevy_pbr",
    "bevy_picking",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_sprite_picking_backend",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_picking_backend",
    "bevy_window",
    "bevy_winit",
    "custom_cursor",
    "default_font",
    "hdr",
    "multi_threaded",
    "png",
    "smaa_luts",
    "sysinfo_plugin",
    "tonemapping_luts",
    "webgl2",
    "x11"
] }
bytemuck = "1.21.0"

[dev-dependencies]
bevy-inspector-egui = "0.28"
bevy_mod_debugdump = "0.12"

[[example]]
name = "fog_of_war_2d"
path = "examples/2d.rs"
required-features = ["2d"]